version: '3.8'

services:
  db:
    image: postgres
    ports:
      - 5469:5432
    environment:
      - POSTGRES_USER=hw
      - POSTGRES_PASSWORD=hw
      - POSTGRES_DB=hw

  server:
    build: .
    ports:
      - 3000:80
    environment:
      - POSTGRES_URL=postgresql://hw:hw@db:5432/hw
      - MONGODB_URL=mongodb://username:password@mongo:27017/todos?authSource=admin

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - db:/data/db
      - configdb:/data/configdb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://username:password@host.docker.internal:27017/

volumes:
  db:
  configdb:
