version: '3.8'

services:
  db:
    image: postgres
    ports:
      - 5469:5432
    environment:
      - POSTGRES_USER=hw
      - POSTGRES_PASSWORD=hw
      - POSTGRES_DB=hw

  server:
    build: .
    ports:
      - 3000:80
    environment:
      - POSTGRES_URL=postgresql://hw:hw@db:5432/hw
