version: '3.8'

services:
  db:
    image: postgres
    ports:
      - "5469:5432"
    environment:
      - POSTGRES_USER=hw
      - POSTGRES_PASSWORD=hw
      - POSTGRES_DB=hw

  server:
    build: .
    ports:
      - "3000:80"
    environment:
      - NULLSTONE_ENV=localhost
      - POSTGRES_URL=postgresql://hw:hw@db:5432/hw
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-datadog:4318

  otel-datadog:
    image: nullstone/otel-collector
    command: ["--config=/etc/datadog/collector.yml"]
    ports:
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
    environment:
      - DD_API_KEY=
