version: '3.8'

services:
  db:
    image: mysql:8
    ports:
      - "3406:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=hw
      - MYSQL_USER=hw
      - MYSQL_PASSWORD=hw
      - MYSQL_DATABASE=hw

  server:
    build: .
    ports:
      - "3000:80"
    environment:
      - MYSQL_URL=mysql://hw:hw@db:3306/hw
