name: Build and Push Artifact

on:
  workflow_dispatch:
    inputs:
      NULLSTONE_ORG:
        description: 'The Nullstone organization for the application being built'
      NULLSTONE_STACK:
        description: 'The Nullstone stack for the application being built'
      NULLSTONE_APP:
        description: 'The Nullstone app that is being built'
      NULLSTONE_ENV:
        description: 'The Nullstone environment for the application being built'
      NULLSTONE_VERSION:
        description: 'The Nullstone version for the application being built'
      NULLSTONE_COMMIT_SHA:
        description: 'The Nullstone commit sha for the application being built'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '16'

      # - name: Install dependencies
      #   run: yarn install

      # - name: Run tests
      #   run: npm test

      # - name: Build application
      #   run: npm run build

      - name: Build docker image
        run: |
          docker build -t ${{ inputs.NULLSTONE_APP }}:${{ inputs.NULLSTONE_VERSION }} .

      # - name: Save Docker image as tarball
      #   run: |
      #     docker save -o docker-image.tar ${{ inputs.NULLSTONE_APP }}:${{ inputs.NULLSTONE_VERSION }}

      # - name: Upload Docker image as artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: docker-image
      #     path: docker-image.tar
      #    retention-days: 7

      - uses: nullstone-io/setup-nullstone-action@v0
      - name: Nullstone push
        env:
          NULLSTONE_API_KEY: ${{ secrets.SSICKLES_NULLSTONE_API_KEY }}
          NULLSTONE_ORG: ${{ inputs.NULLSTONE_ORG }}
          NULLSTONE_STACK: ${{ inputs.NULLSTONE_STACK }}
          NULLSTONE_APP: ${{ inputs.NULLSTONE_APP }}
          NULLSTONE_ENV: ${{ inputs.NULLSTONE_ENV }}
        run: nullstone push --source=${{ inputs.NULLSTONE_APP }}:${{ inputs.NULLSTONE_VERSION }} --version=${{ inputs.NULLSTONE_VERSION }}
        shell: bash
