name: Build and Push Artifact

on:
  workflow_dispatch:
    inputs:
      NULLSTONE_STACK:
        description: 'The Nullstone stack for the application being built'
        required: true
      NULLSTONE_APP:
        description: 'The Nullstone app that is being built'
        required: true
      NULLSTONE_ENV:
        description: 'The Nullstone environment for the application being built'
        required: true
      NULLSTONE_VERSION:
        description: 'The Nullstone version for the application being built'
        required: true
      NULLSTONE_COMMIT_SHA:
        description: 'The Nullstone commit sha for the application being built'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '16'

      # - name: Install dependencies
      #   run: yarn install

      # - name: Run tests
      #   run: npm test

      # - name: Build application
      #   run: npm run build

      - name: Build docker image
        run: |
          docker build -t ${{ github.sha }} .

      - name: Save Docker image as tarball
        run: |
          docker save ${{ github.sha }} -o image.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: image.tar
